### PR TITLE
added A1LU6

### PR DESCRIPTION
**Pull request by wojdyr**
I tried it out with gemmi. It works as expected.
Let's add it to master branch for better visibility and easier testing.

### CODE REVIEW

**Comment by keitaroyam** [comment]
It should be tested at least with Refmac and Coot before merging to master.

**Comment by wojdyr** [comment]
These programs don't support long monomer names, so they won't be able to use them.
 
@pemsley We discuss adding a monomer file with 5-character code. Would Coot simply ignore it?

**Comment by keitaroyam** [comment]
I'm a bit worried because Refmac reads the entire library. We just have to do some tests to see this won't harm CCP4 programs.

**Comment by GaribMurshudov** [comment]
With refmacat refmac should read the library. CCP4 is switching to refmacat. I think we should make sure that all pipelines use refmacat (and we need to add an alias so that only refmacat is used)

**Comment by keitaroyam** [comment]
Just tested Refmac (not refmacat). It was ok for structures not containing A1LU6. Also ok for A1L-containing structures. Not sure about other CCP4 programs including Coot.
Refmacat works (needs the latest version from github)

**Comment by GaribMurshudov** [comment]
refmac worked? I guess with your additional script. 
I see: not containing
We would like refmacat to work

**Comment by wojdyr** [comment]
What other programs, not mentioned above, use the monomer library?
perhaps CCP4MG @stuartjamesmcnicholas

**Comment by stuartjamesmcnicholas** [comment]
Certainly CCP4MG. Moorhen also.

**Comment by keitaroyam** [comment]
Is it possible to test the CCP4 programs using this branch?

**Comment by keitaroyam** [comment]
Now there are 65 five-letter codes.. (all starting with A1)

**Comment by GaribMurshudov** [comment]
Should we update them in our monomer library.

And I think they start with A1 now, later, in couple of years other letters also will be present

**Comment by keitaroyam** [comment]
At some point I think we want to add all new entries to the library. It's great if all programs are ready for 5-letter codes.. Did anyone test this with Coot (and others)?

**Comment by keitaroyam** [comment]
Just tested Coot 0.9.8.92 from CCP4, and it seems fine (Get Monomer and Search Monomer Library worked)

**Comment by GaribMurshudov** [comment]
I can approve this.

**Review by GaribMurshudov — COMMENTED** [review]
I think it is time to approve this. Let others to test this also.

**Review by GaribMurshudov — APPROVED** [review]

**Comment by CV-GPhL** [comment]
Slightly off-topic and maybe not completely related to a pull-request decision, here are some notes about validating the proposed file against the latest [PDBx/mmCIF v5.0](https://github.com/wwpdb-dictionaries/mmcif_pdbx) dictionary:

```
ERROR - In block "comp_list", in category "chem_comp", item "group" is not defined in the reference file
ERROR - In block "comp_list", in category "chem_comp", item "desc_level" is not defined in the reference file
ERROR - In block "comp_list", mandatory item "type" is not in category "chem_comp"
```

* _chem_comp.group should probably be [_chem_comp.type](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_chem_comp.type.html)  which would also fix the error about missing mandatory item
* Is _chem_comp.desc_level actually ever set in any file? I can't find any so far ...)

```
ERROR - In block "comp_A1LU6", in category "chem_comp_atom", item "type_energy" is not defined in the reference file
```

* would be great to have this added to the PDBx/mmCIF dictionary

```
ERROR - In block "comp_A1LU6", in category "chem_comp_atom", item "x" is not defined in the reference file
ERROR - In block "comp_A1LU6", in category "chem_comp_atom", item "y" is not defined in the reference file
ERROR - In block "comp_A1LU6", in category "chem_comp_atom", item "z" is not defined in the reference file
```

* These should probably be [_chem_comp_atom.model_Cartn_{x,y,z}](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_chem_comp_atom.model_Cartn_x.html) (or  [_chem_comp_atom.pdbx_model_Cartn_{x,y,z}_ideal](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_chem_comp_atom.pdbx_model_Cartn_x_ideal.html))

```
ERROR - In block "comp_A1LU6", category "chem_comp_acedrg" is not defined in the reference file
```

* namespacing usually happens as a prefix, not as a suffix. It also usually is based on an "organisation" name like "pdbx", "ccp4" or "gphl" - so "ccp4_chem_comp" would be more in line with all others (see e.g. "_pdbx_chem_comp_pcm", "_ccp4_refine_tls_group" etc)

```
ERROR - In block "comp_A1LU6", in category "chem_comp_bond", item "type" is not defined in the reference file
```

* That should probably be [_chem_comp_bond.value_order](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_chem_comp_bond.value_order.html) with its defined vocabulary
  
```
ERROR - In block "comp_A1LU6", in category "chem_comp_bond", item "aromatic" is not defined in the reference file
```

* That should probably be [_chem_comp_bond.pdbx_aromatic_flag]( https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_chem_comp_bond.pdbx_aromatic_flag.html)

```
ERROR - In block "comp_A1LU6", in category "chem_comp_bond", item "value_dist_nucleus" is not defined in the reference file
ERROR - In block "comp_A1LU6", in category "chem_comp_bond", item "value_dist_nucleus_esd" is not defined in the reference file
```

* should be added to the dictionary (and the dictionary should be extended to clarify that the non-nucleus items refer to e-cloud positions when X-Ray is involved)

```
ERROR - In block "comp_A1LU6", in category "chem_comp_tor", item "value_angle" is not defined in the reference file
ERROR - In block "comp_A1LU6", in category "chem_comp_tor", item "value_angle_esd" is not defined in the reference file
ERROR - In block "comp_A1LU6", in category "chem_comp_tor", item "period" is not defined in the reference file
```

* These should be added into the dictionary (unless we want to stick with the current chem_comp_tor definition and extend the [chem_comp_tor_value](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/chem_comp_tor_value.html) category by a periodicity value ... )

```
ERROR - In block "comp_A1LU6", category "pdbx_chem_comp_description_generator" is not defined in the reference file
```

* that looks like a typo ... should that not be the ["pdbx_chem_comp_descriptor"](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/pdbx_chem_comp_descriptor.html) category?

**Comment by GaribMurshudov** [comment]
@CV-GPhL these are good points. Some of the items are there because of the history of the monomer library. However, we need to add new descriptons, and make acedrg as prefix not suffix. 
@flong-mrc would it be possible to address the points related to acedrg.

**Comment by keitaroyam** [comment]
* _chem_comp.group vs type: "type" has a list of allowed items, which is not compatible with the monomer library.
* perhaps we don't need desc_level?
* chem_comp_atom.model_Cartn_{x,y,z}_ideal: the recent acedrg writes this and {x,y,z}. Personally I don't want duplicated data
* chem_comp_bond.type and aromatic: the recent acedrg uses value_order and pdbx_aromatic_flag

**Comment by CV-GPhL** [comment]
If the controlled vocabulary in [_chem_comp.type](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_chem_comp.type.html) needs extending, it should be very easy to do so.

The ML seems to contain the following values atm
```
   N       ML             _chem_comp.type
-----------------------------------------------------------
33886    NON-POLYMER     non-polymer
  669    peptide         peptide-like / peptide linking
  338    pyranose        ?
  138    DNA             DNA linking
  100    RNA             RNA linking
   30    M-peptide       ?
   27    P-peptide       ?
   17    furanose        ?
    5    ketopyranose    ?
```

As you can see, most of the names currently already present have no detailed explanation: it would be good to add this too (so we know what "M-peptide" or "P-peptide" actually means).

**Comment by drlemmus** [comment]
The types in the ML describe how compounds link whereas the CCD types describe more chemical classes. They reflect different ways of thinking and different goals. If the ML(-format) users agree I think it is better to put the ML data in a different item.

**Comment by keitaroyam** [comment]
Updated using the latest Acedrg (no manual work was needed)

**Comment by keitaroyam** [comment]
Merged. We can continue the discussion in Issues or Discussions.

**Pull request merged**
