### PR TITLE
From pdb redo testing

### PR DESCRIPTION
**Pull request by drlemmus**
Please add the new compounds and merge in the change for EXA to stay compatible with the PDB archive.

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
Should we test them first? I am worried that the number of monomers is becoming very large and they may have not been tested as carefully as we would like. 
Who else can do testing. I know that Robbie does tests as a part of PDB-REDO. Keitaro does a lot of testing. We need one more person for independent testing.

**Comment by drlemmus** [comment]
We could also have a different approach where we actively pursue feedback from users and do rapid fixing. That way we can focus more on the technical testing. The update mechanism of CCP4 allows this approach and now that the library in on GitHub we have a good channel for feedback and fixes.

**Comment by keitaroyam** [comment]
I think I will check them. Regarding EXA, unfortunately the nomenclature does not follow the standard: EXA's NH3 hydrogen atoms are H1/H2/H3, instead of H/H2/H3. It can be solved by the alias mechanism, which I will add soon.

**Comment by drlemmus** [comment]
This should be reported to the PDB. I'll add it to my monthly bug digest. I'm not so hydrogen oriented, so I overlooked that.

**Comment by GaribMurshudov** [comment]
> We could also have a different approach where we actively pursue feedback from users and do rapid fixing. That way we can focus more on the technical testing. The update mechanism of CCP4 allows this approach and now that the library in on GitHub we have a good channel for feedback and fixes.

It is a good idea. @keitaroyam we should announce github repository with specific aim that we would like community testing and feedback. @drlemmus and @keitaroyam can coordinate this.

**Comment by GaribMurshudov** [comment]
> This should be reported to the PDB. I'll add it to my monthly bug digest. I'm not so hydrogen oriented, so I overlooked that.

I think it is time to have feedback mechanism with the PDB also. They claimed that they will use whatever we offer (within reason of course)

**Comment by drlemmus** [comment]
A formal feedback route for the CCD at the PDB would be great. Currently I send a monthly digest of the issues I've found to the annotators at PDBe/RCSB/PDBj, but this mostly refers to the model and reflection data files. I sometimes give feedback on CCD entries but not quite as systematic.

**Comment by glycojones** [comment]
>
> We could also have a different approach where we actively pursue feedback
> from users and do rapid fixing. That way we can focus more on the technical
> testing. The update mechanism of CCP4 allows this approach and now that the
> library in on GitHub we have a good channel for feedback and fixes.
>
This is a great idea!

-- 
Dr Jon Agirre [image: A button with "Hear my name" text for name playback
in email signature]  <https://www.name-coach.com/jon-agirre>
Royal Society University Research Fellow
CCP4 ED&I champion | instruct-ERIC representative @ 3D-Bioinfo (Elixir)
York Structural Biology Laboratory, Department of Chemistry
University of York, Heslington, YO10 5DD, York, UK
http://www.york.ac.uk/chemistry/research/ysbl/people/staff/jagirre/
Office: /B/K/065 Phone: +44 (0) 1904 32 8252
Twitter: @glycojones

**Comment by keitaroyam** [comment]
Here is already open, and anyone can contribute via issue or PR. I will also add a simple automatic test when the next gemmi is released. Then we can announce, I think.

Atom names and groups: more than hundreds of monomers do not follow the standard. So I thought our decision is to introduce the alias mechanism, which is now supported by gemmi (and eventually by refmac via servalcat).

**Comment by drlemmus** [comment]
The alias mechanism is a great workaround, but catching the issue at the source should be a goal. Anyway, if you want changes in the CCD, I'm happy to relay the issue.

**Comment by GaribMurshudov** [comment]
We should work in two directions: 1) Alias mechanism. It will increase flexibility and solve many problems now and later; 2) We should try to make the monomer library a bit more standard. It is a long term goal. But since many players are involved it may take very long time to sort things out.

**Comment by keitaroyam** [comment]
I added changes:
- made const* torsion angles sigmas zero (just for consistency. Refmac does not use them in any case)
- demoted EXA to NON-POLYMER

**Comment by keitaroyam** [comment]
Apart from that, they look good to me.

**Pull request merged**
