### PR TITLE
From pdb redo testing

### PR DESCRIPTION
**Pull request by drlemmus**
I think things are clean now, but do check.

### CODE REVIEW

**Comment by keitaroyam** [comment]
I think we can check these new monomers this week or next. Some quick comments:

* K39: we may need to change _chem_comp.group from RNA to NON-POLYMER.
* P3C: metal containing
* Following atoms have strange geometry in idealised models
  * BJ3: H52/H53/H54/H85
  * BQG: H81/H48/H49/H50
  * I1X: around N16

Perhaps the strange geometry is due to a bug of Refmac that has been fixed in the latest version. We should try it.

**Comment by drlemmus** [comment]
Are you sure for K39? The atom names are RNA compatible and that would keep users from.having to define two new linkages

**Comment by keitaroyam** [comment]
K39: the problem is SP1 atom instead of OP1. SP1-P-O3' angle restraint will be missing, if we use the p link. We demoted this kind of monomer to NON-POLYMER in CCP4 8.0, although it is not very problematic in this case.

**Comment by keitaroyam** [comment]
BJ3/BQG/I1X: I tried Refmac5.8.0403 and idealised structures look all good. I pushed these files, so please check them.

It was a bit strange some value_angle_esd have changed. Did you do anything after acedrg? I just used PDB provided cif file with -c option.

**Comment by drlemmus** [comment]
I use asu : 3.5 asl : 0.5 to keep some dynamic range on the angles. The default range is too narrow to show the difference between angle variance IMO

**Comment by keitaroyam** [comment]
If it is scripted, can you run it for these three cif files? I suppose you also fixed cif file to be coot (mmdb) friendly. If some manual works needed, I will revert the commit and just replace coordinates.

**Comment by drlemmus** [comment]
Nope, I only ran AceDRG, using the released version, no manual editing. The dynamic range for angles was chosen to be consistent with the restraints for proteins and nucleic acids (EH and nucleic acid working group)

**Comment by keitaroyam** [comment]
OK, done. I actually didn't know --asu and --asl options.

Just out of curiosity, what cif did you use for input? The problem is Coot (I guess mmdb) fails with
```
loop_
_pdbx_chem_comp_descriptor.comp_id
_pdbx_chem_comp_descriptor.type
_pdbx_chem_comp_descriptor.program
_pdbx_chem_comp_descriptor.program_version
_pdbx_chem_comp_descriptor.descriptor
BJ3 InChI            InChI                1.06  "InChI=1S/C62H84N11O9PS/c63-61(64)66-36-20-34-56(83(80,81-45-25-10-3-11-26-45)82-46-27-12-4-13-28-46)72-60(78)51(39-44-40-67-48-30-16-15-29-47(44)48)70-59(77)50(38-43-23-8-2-9-24-43)69-58(76)49(37-42-21-6-1-7-22-42)68-55(75)33-14-5-19-35-65-54(74)32-18-17-31-53-57-52(41-84-53)71-62(79)73-57/h1,3-4,6-7,10-13,15-16,21-22,25-30,43-44,49-53,56-57,67H,2,5,8-9,14,17-20,23-24,31-41H2,(H,65,74)(H,68,75)(H,69,76)(H,70,77)(H,72,78)(H4,63,64,66)(H2,71,73,79)/t44-,49-,50+,51+,52?,53?,56-,57?/m1/s1"
```
but ok with
```
loop_
_pdbx_chem_comp_descriptor.comp_id
_pdbx_chem_comp_descriptor.type
_pdbx_chem_comp_descriptor.program
_pdbx_chem_comp_descriptor.program_version
_pdbx_chem_comp_descriptor.descriptor
BJ3 InChI            InChI                1.06
;InChI=1S/C62H84N11O9PS/c63-61(64)66-36-20-34-56(83(80,81-45-25-10-3-11-26-45)82-46-27-12-4-13-28-46)72-60(78)51(39-44-40-67-48-30-16-15-29-47(44)48)70-59(77)50(38-43-23-8-2-9-24-43)69-58(76)49(37-42-21-6-1-7-22-42)68-55(75)33-14-5-19-35-65-54(74)32-18-17-31-53-57-52(41-84-53)71-62(79)73-57/h1,3-4,6-7,10-13,15-16,21-22,25-30,43-44,49-53,56-57,67H,2,5,8-9,14,17-20,23-24,31-41H2,(H,65,74)(H,68,75)(H,69,76)(H,70,77)(H,72,78)(H4,63,64,66)(H2,71,73,79)/t44-,49-,50+,51+,52?,53?,56-,57?/m1/s1
;
```

**Comment by drlemmus** [comment]
I use the ones from http://ligand-expo.rcsb.org/reports/$C1/$HETID/${HETID}.cif

My guess is that the size limitations for text and multi-line text in Coot/mmdb are different.

**Comment by keitaroyam** [comment]
Maybe. We found Coot on Mac did not have this problem.. The problem happened on Linux. 
Edit: Pual's build for Linux works. CCP4's Linux build seems to have the problem.
Edit2: reported to CCP4 people

**Comment by keitaroyam** [comment]
We found a problem in BJ3 torsion angles:
```
BJ3            sp2_sp2_29         CCU         CCT         OCS         PAD     180.000     5.0     2
BJ3            sp2_sp2_43          C2          C1         OAE         PAD     180.000     5.0     2
```
These are obviously wrong. Reported to Fei.

**Comment by keitaroyam** [comment]
WEL has wrong chirality (I guess libcheck was used?). But Acedrg puts wrong torsion angle around C19-S1 (related to the problem with BJ3). Will wait for Acedrg to be fixed.

Another type of sp2_sp2 problem:
```
I1X            sp2_sp2_21         C21         C23         N24         O25     180.000     5.0     2
```
and
```
ZN1            sp2_sp2_18         C47         C48         C51         O08       0.000     5.0     2
```
these torsion angles would not be 0/180 because of steric clashes, but it may be ok as restraints.

**Comment by keitaroyam** [comment]
@drlemmus I did following updates. Please check the files. If you think they are ok then we can merge them to master.

DJ5/G5F/G7C/CZU/UQO: idealised structures updated using Refmac5.8.0403 to fix strange hydrogen geometry.
BJ3/WEL: updated using Acedrg 264, which does not write sp2_sp2* for those kind of torsion angles. We need further analysis.
I1X/ZN1: For now we will leave them as they are
K39: demoted to non-polymer

**Comment by drlemmus** [comment]
All fine AFAICT

**Pull request merged**
