### PR TITLE
Updated DHE HEB HEC with coordinates from Lucrezia.

### PR DESCRIPTION
**Pull request by rob-nicholls**

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
It is good. In general it would be good if some of us would also test to make sure that changes are correct

**Comment by rob-nicholls** [comment]
For reference, I've added the script used to transplant the coordinates to the Ligand-Tools repository. This is a general script - not specific to these three comp_ids.

**Comment by GaribMurshudov** [comment]
Does the script check if all atoms are present? There may be cases when coordinates or the dictionary has one or two more atoms (mostly hydrogen atoms). This is related with protonation/deprotonation assumption we and PDB differ on.

**Comment by rob-nicholls** [comment]
At present it checks that all atoms in the CIF dictionary are present in the new coordinates file, but not the converse. If useful to check both ways, it is an easy extension.

**Comment by keitaroyam** [comment]
Is the restraint of DHE ok? I see some distortion after regularisation in Coot or Refmac.

**Comment by GaribMurshudov** [comment]
It needs to be checkd. I will chck today.

**Comment by GaribMurshudov** [comment]
I can see several problems with DHE:
1) Fe-NA distance is different than Fe-NB, NC, ND distances. they should be equivalent
2) Fe is in all pyrrol planes by A. 
3) Planarities are much too extended. They should be local

In short: we need to generate new dictionary for this case also. I will wait for Fei to add one thing in AceDRG then I can generate new dictionary for DHE. But we need to generate new dictionaries for all Hem like structures. We can discuss this next week

**Pull request merged**
