### PR TITLE
fix HIS torsion angles

### PR DESCRIPTION
**Pull request by keitaroyam**
plane related part should be const_*

### CODE REVIEW

**Comment by keitaroyam** [comment]
I re-confirmed this with Acedrg 271. I think I can merge it?

**Comment by GaribMurshudov** [comment]
Can you check atom types on His ring nitrogens? They need to be sorted. But it is a different problem.
Yes. merging is a good idea.

**Comment by keitaroyam** [comment]
Acedrg 271 gives the same atom types. Is it related to #14 ?

**Comment by GaribMurshudov** [comment]
I think we should sort out atom types. It includes #14 also. Problems might in cases like His ring where we do not know H atom postions without the context. We need to have some tools to change/fix atom types for these cases. It is also relevant to N atoms with 3 or four bonds (n-terminal N, when it has two H then it is H bond acceptor and donor. When it has 3 H atoms then it can only be H bond donor.

**Comment by keitaroyam** [comment]
OK, let's discuss it there. I close this.

**Pull request merged**
