### PR TITLE
fix H-related issues

### PR DESCRIPTION
**Pull request by keitaroyam**
In #44 I didn't include hydrogen for comparison, knowing acedrg removes/adds hydrogen from carboxyl group/to amine group for example. In #47 an Acedrg bug was reported which reuses removed H atoms and adds CCD-nonexistent bonds. So I checked H atom related inconsistencies.

Here the dictionaries of following entries have been regenerated using Acedrg 285.
```
0HH 0MU 0TD 1CC 28X 2SO 2ZC 3GE 3QN 3VN 432 4OV 4R2 56W 5S4 60F 6CX 6H5 6N9 6NC 73C 73N 78G 78K 7N6 7XC 8Y9 9E7 9RN 9TU 9U0 9VR AM1 AT1 B8N BD0 BXT C1X CGV CYJ E6F EDX EGV EJA EXR FAK FOD FYG GBS GXB HGY HIQ HJ2 HJ8 HJT ILY J9A JSP JX7 K5T KUN KYE LEE LPR M88 MQ4 MRC N65 NCG NXL OBS P00 P5U P9S PN1 PVK Q3G Q3S QNQ QNT QO2 QO5 SNK SVV UOX UXQ V7D V7T VR0 Y3S ZU0 ZZ7
```
The followings need to be fixed but contain metals.
```
8CY CHL CL0 REQ RHL
```

Again there seems to be inconsistencies between PDB and CCD. For example 1CC has C6-H10 bond in the CCD but 4m9v has C6-H6 bond (so our current dictionary is valid). Perhaps this should not be merged now.

### CODE REVIEW

**Comment by keitaroyam** [comment]
Further inconsistencies were found and updated using Acedrg 290.
```
0HH 02L 02O 05J 0FL 0RJ 2AG 2AS 2HF 2NO 2RA 2V9 30V 35Y 3AH 3AR 3EG 3GE 3M7 4AK 4IN 4PH 4QK 51B 5CS 5FD 5R5 5T3 6CV 6FL 6M6 6YG 7ID 8RE 8SP 9TX 9U6 9U9 9UC 9UF 9V0 9V6 9VC 9VL ACB AGQ AP0 B3U BGQ BTK BUC C2N C5C C6C CLG CLH CMT CS3 CS4 CSA CT6 CTE CYD CYG DHV DJD DKE DNS DO2 DON E9C E9V ECX EFC ELY EXA EXC EXY F9D FOE G01 GLJ GME GNC GSC GT9 GXB HCM HHK HJV HJY HRP HTI HTN HVA HWN I58 IMH IRE KJW KPI KYN LBY LCK LME LMF LMQ LVG LVN LYH LYX MBQ MD3 MD5 MDF MEG MIS MLZ MMO MTN MYK NBQ NMM NO NPI OAS OMH ORQ OTH PEC PMW PRK PTH QMM QVA R0N R1A R1B R1F R2P R2T R4K R7A RCY RFQ RXR S1H S2P SC2 SDP SHC SLL SMC T9E TLY TQZ TRF TSY TTQ TY1 TYJ TYQ UB4 UGY UNK UX8 V1A V5N VAH XFW XX2 XYC Y57 Z01 ZBZ
```

Following entries still have inconsistencies even after updating, presumably because of wrong chemistries (reported to PDB)

EJA: OZH atom is named HOZ in 6c4c
3GE: SO2 moiety should have -1 charge and one double bond
DKE: C70 atom has two hydrogen atoms. Either H53 or H54 should be removed
GXB: NAD atom is marked as radical, but I suppose a hydrogen atom should be bound?
RFQ: likewise, N27 atom should not be radical and have hydrogen bound?

NO also has a problem, which needs to be handled on our side.
XX2 also has a radical issue, and it seems at least [intentional](https://doi.org/10.1126/science.1134697).

The 1CC issue will be sorted next week; see https://github.com/MonomerLibrary/monomers/issues/47#issuecomment-2082912247

**Comment by keitaroyam** [comment]
EJA and 3GE have been updated, as their definitions were changed in the CCD.

How can we handle NO?

**Comment by GaribMurshudov** [comment]
For NO we should add -1 on N. Then acedrg will work. Otherwise it is a radical. I think in all stable structure NO will be bound to a metal or something else. So, -1 on N should not be bad.

**Comment by keitaroyam** [comment]
I think this branch now should be reviewed and hopefully merged.
Noted unsorted issues https://github.com/MonomerLibrary/monomers/wiki/Known-problems

**Review by GaribMurshudov — APPROVED** [review]
I think this has been sorted

**Pull request merged**
