### PR TITLE
fix RNA/DNA energy types

### PR DESCRIPTION
**Pull request by keitaroyam**
Because of acedrg bug, now there are wrong energy types. Some of them affect critical distances in nonbonded interactions and can break base pairs for example. They were partly fixed in ceef1a2201536d23e35daeb0d16ab9c73c2aed79.
This is a quick fix of energy types that affect hydrogen bonds for all RNA/DNA. It includes NT -> NR5, NR5 -> NR15, and NR6 -> NR16.

I did not include following changes. All monomers need to be updated at some point.
```
6OG O6   : O2   -> O  
6PO O6   : O2   -> O  
70U O9   : O2   -> O  
BMN O37  : O2   -> O  
C6G O6   : O2   -> O  
EHG O6   : O2   -> O  
EXC O10  : O2   -> O  
EXC O21  : OH1  -> OC  
HOL O8   : O2   -> O  
MM7 O1   : O2   -> O  
RDG O7   : O2   -> O  
T0T N15  : NT2  -> NH2
T5O O5   : O2   -> O  
TC1 N5   : NT1  -> NR16
UPV OB1  : O2   -> O  
YCO O14  : O2   -> O  
YG  O18  : O2   -> O  
YG  O23  : O2   -> O  
YYG O18  : O2   -> O  
YYG O23  : O2   -> O  
```

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
We do not to update these and test a bit more carefully. Not like last time.

**Comment by keitaroyam** [comment]
Do you mean by "these" whole monomer dictionaries or only certain energy types (as in this commit)?

**Comment by GaribMurshudov** [comment]
Let me test one thing then I will see if we need to update all critical monomers or we can update energy types. 
I have added in refmac NRx --> NR1x for cases when there are two non-hydrogen bonds. I can add few more such changes based on the number of bonds.
In the list you gave above atomic radii (vdw, ionic) and HB capability are same for those pairs apart from OH1 --> OC. OH1 is donor/acceptor, OC is acceptor only.

**Comment by keitaroyam** [comment]
I am afraid changing program for wrong dictionaries is not a good way. Dictionary should be fixed if it is wrong, no?
That listed changes **not** included in this commit. Some of them do not changes hb_types and some of them should involve changes of ideal values.

**Comment by GaribMurshudov** [comment]
Although I agree but for finding out errors I can change the program and then remove that part of the code.

**Pull request merged**
