### PR TITLE
fix peptides having incomplete termini

### PR DESCRIPTION
**Pull request by keitaroyam**
Following peptides did not have proper terminal groups (missing OXT, or N with H or H2) and they cannot be "peptide" group in our definition.

31Q CSR CZZ CMH CAS C4R CAF CSB CZ2 SVA

Of these, following include As, which now we can regenerate using Acedrg (here v271 was used): CSR CZZ CAS CAF CZ2

The rest have metals, and we decided to remove: 31Q (Hg), CMH (Hg), C4R (Rh), CSB (Pb), SVA (V)

Regarding As-X bonds, it seems some high resolution PDBs have very different values from (our) ideals. PDB validation does not check these bonds, as Mogul stats could not be retrieved I guess.
```
2xnq:
        atom1        atom2  value  ideal      z
 A/CAF 383/O1 A/CAF 383/AS  1.955  1.662 29.261
A/CAF 383/CE2 A/CAF 383/AS  1.988  1.895  9.252
A/CAF 383/CE1 A/CAF 383/AS  1.977  1.895  8.166

2iwr:
       atom1         atom2  value  ideal      z
A/CAF 212/AS  A/CAF 212/O1  1.950  1.662 28.793
A/CAF 200/AS  A/CAF 200/O1  1.933  1.662 27.056

1j9b:
        atom1         atom2  value  ideal       z
A/CZZ 12/AS.A A/CZZ 12/O1.A  1.851  1.760   9.056
```

Note that CZZ has As radical and Acedrg cannot handle it (adds a hydrogen atom). We manually removed the hydrogen.

### CODE REVIEW

**Comment by drlemmus** [comment]
So how would that work in practice if I have to refine a model that contains the deleted compounds? Is it not better to have a sort of best-effort restraint file (made by libcheck I suppose)?

Good work on the other compounds of course.

**Comment by GaribMurshudov** [comment]
Obviously, if we remove compounds from the monomer library then we need to have a mechanism of dealing with them. For some cases we could just divide them into different components and use link mechanism. If we go for this then we should not expect that users will do partitioning. It should be done within pipelines.

**Comment by keitaroyam** [comment]
So what to do here? Revert? It's nice if we can somehow modify main chain..

Problem is not only about monomers deleted. We cannot add new monomers with metals..

**Comment by GaribMurshudov** [comment]
Either somebody designs a sufficiently accurate descriptions for these ligands or we remove them. 

We could use an algorithm we discussed sme time ago: remove metal, use acedrg to generate ligand description without metal, add metal with bond lengths and perhaps angles into the the ligand cif file, optimise and update ligand description file.

**Comment by keitaroyam** [comment]
Can you list up ideal values?
31Q, CMH: C-Hg, S-Hg, C-C-Hg, C-Hg-S, C-S-Hg
CSB: S-Pb, C-S-Pb

How do we handle C4R and SVA?

**Comment by GaribMurshudov** [comment]
For SVA I would do five coordinated V and a link with the Ser residue where one of the O's from V is replaced by OG.
Or (I think this should be better): Use four waters and V. then link V with waters and OG of Ser (with removal of HG)

C4R requires more thinking. As I can see from the PDB file there is an octahedral Rh with three waters, one O of Glu, one Sg of Cys and two of C of the ligand coordinating. Last two C atoms act as one. 
I would create; description of the ligand without metal, and links between Rh and this ligand C atoms (there will be two bonds), link between Rh and Glu and link between Rh nd Sg. And finally: link between Sg and the ligand.
It sounds very complicated, I agree

**Comment by GaribMurshudov** [comment]
> Can you list up ideal values? 31Q, CMH: C-Hg, S-Hg, C-C-Hg, C-Hg-S, C-S-Hg CSB: S-Pb, C-S-Pb
> 
> How do we handle C4R and SVA?

I will try to find these and send yiu the distances and share soon.

**Comment by keitaroyam** [comment]
SVA/C4R: do you mean we will have the monomer descriptions without metals?

For C4R, it may be sufficient to just have ideal distances for Rh-S and Rh-C. I can try if you give these values.

**Comment by GaribMurshudov** [comment]
```
### Metla-Ligand      Mean    Sd      Median     Mad     Nobs           Mode1      Mode2   ...       distribution       
Hg-C                  2.075    0.024     2.074     0.0172   919                                                 unimodal
Hg-S                  2.541      0.166   2.508      0.149    937            2.41         2.52              multimodal and skewed. 
Pb-S                   3.245     0.386   3.22      0.51        857            2.951       3.64              Bimodal and skewed
```
I do not ave angles. I think for these cases we may use simple anges
```
Rh-S                 2.35        0.057     2.356    0.047    1181         2.170         2.37             Bimodal. First mode is only 3% of total
Rh-C                2.128       0.120     2.148     0.082   14955      1.90         1.86    2.033  2.14   First mode 3%, second 7% third 12 
```

**Comment by GaribMurshudov** [comment]
Are those numbers readoable. For Rh I would say angles are 90 or 180. Apart from C-Rh-C (it is missing in the picture but visible in the PDB file). I would not put C-Rh-C angle restraints at all. There is double bond C=C and as if this double bond is coordinating Rh

**Comment by keitaroyam** [comment]
Isn't Pb-S distance of 3.22 A too long? I checked some COD structures and they were ~2.7-3.0 A.

**Comment by GaribMurshudov** [comment]
Yes. 3.22 is too long. I think 2.95 is more likely. current histogram has two peaks. One at around 2.95 and another one around 3.64. I thought, one of them correspond to actual distances for Pb-S and another one could be on the second coordination sphere.

**Comment by keitaroyam** [comment]
31Q, CMH, C4R, and CSB were regenerated.

I don't know what we can do for SVA (V containing).

**Comment by GaribMurshudov** [comment]
i need to think about this a bit. It is tempting to keep it for now with some manual curation. However, it would not be possible to do this all the time for many ligands. Dividing into two with a link is another good option. Then programs should understand what is happening.
As I see, in the PDB there is only one entry with this ligand. How much time should we spend on this?

**Comment by keitaroyam** [comment]
OK, I will take previous SVA and just fix NH3.

**Comment by GaribMurshudov** [comment]
Ok.

**Comment by keitaroyam** [comment]
SVA is back. We can merge them if these things and As distances are good.

**Comment by GaribMurshudov** [comment]
Fei showed As-O histogram. There are not many data points. But it seems that there are 3-4 modes. One of them is around 1.66
Another question is: what is the bond order As-O in CAF(?). I looked at the density - 1sng and 1hyv. There is one strong atom linked to As. The distance seemed to be 1.66 or so. Another weak density. And As is linked to Sg. 
I did not see any other atoms around As. And O bound to As does not make any interaction with anything arond. I do not know what to make of this. does this mean that CAF is incorrect?

**Comment by keitaroyam** [comment]
I checked 3s2s where it's modeled as CYS+CAD. It looks more convincing..

**Comment by GaribMurshudov** [comment]
I like CYS+CAD option. It keeps amino acid name intact and addition is added as another ligand + link. And, indeed, 3s2s looks more convincing. O makes H bond. Only one worry could be there. One of C atoms on As makes close contact with the main chain O. But it could happen.

**Pull request merged**
