### PR TITLE
remove deuterium-containing monomers

### PR DESCRIPTION
**Pull request by keitaroyam**
DOD, ND4, SPW, and TSD have deuterium atoms and the monomer descriptions are wrong (nitrogen atoms are used for deuterium).

Most of them have hydrogen versions and they should be used in Refmac refinement.
DOD -> HOH
ND4 -> NH4
SPW -> SPK
TSD -> no hydrogen version

Note that ND4 and NH4 have different hydrogen names (D1 vs HN1). For SPW/SPK, some atom names are different.

### CODE REVIEW

**Comment by LucreziaCatapano** [comment]
first silicon-containing monomer generated by AceDRG.

**Comment by GaribMurshudov** [comment]
Now acedrg should be able to generate Si, Se and Ge containing ligands (there is no Ge in the PDB for some reason)

**Comment by keitaroyam** [comment]
D3O monomer is added. I used acedrg -z, and manually changed energy type of O.

**Comment by keitaroyam** [comment]
D8U (deuterium ion) is added for completeness. Note that critical distance of nonbonded interaction may be inappropriate; e.g. in 4AR3 the distance between D (D8U) and OD2 (GLU) is 1.7 A while Refmac would put 2.6 A as an ideal distance.

**Comment by GaribMurshudov** [comment]
Ok. I will change refmac. This particular ion (is it +1?) should be treated as if it is from H bond donor. 
What do we do with H^(-1)? This should be treated as a separate entity, it can make interaction with metals. How about its involvement in H-H interactions? I would assume that such interactions would be rare.

**Pull request merged**
