### PR TITLE
update p link

### PR DESCRIPTION
**Pull request by keitaroyam**
Updated using acedrg v249 with following instruction.
```
LINK: RES-NAME-1 U ATOM-NAME-1 O3' RES-NAME-2 U ATOM-NAME-2 P DELETE ATOM OP3 2
```

The problem was in C3'-O3'-P angle which was 109.471.

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
Ok. Can anybody make new p link and compare with what is in the library. We should also update RNA-F86 and similar links if available.

**Comment by GaribMurshudov** [comment]
Ok. I see that Keitaro has done it. 
At the moment my acedrg does not work. So, I cannot change it.

**Comment by keitaroyam** [comment]
RNA-F86 would not be needed if alias mechanism is introduced, but I will update it for compatibility.

**Comment by GaribMurshudov** [comment]
Yes, you are right. But it would be a test for AceDRG

**Comment by keitaroyam** [comment]
RNA-F86 link has been updated with the following instruction
```
LINK: RES-NAME-1 U ATOM-NAME-1 O3' RES-NAME-2 F86 ATOM-NAME-2 P1 DELETE ATOM O7 2 CHANGE CHARGE 2 O5 0 CHANGE BOND O5 P1 DOUBLE 2
```

At the moment in the PDB F86 presents in four structures as part of polymer. This link works for three of them, but not for one that removes O5 atom instead of O7. In the first place O7 is not OP3 equivalent atom. This needs a general solution.

**Comment by keitaroyam** [comment]
Good news from @deborahharrus: F86 has been fixed, and now in all entries O7 of F86 is used as a leaving atom.

**Pull request merged**
