### PR TITLE
reflecting changes in the CCD

### PR DESCRIPTION
**Pull request by keitaroyam**
Following #40, inconsistencies from the CCD was checked.

Now, following entries are obsolete:
```
2VO 39E E7U F3O LL8 M60 ON8 PSD QHD RTV SOC T0Q YYQ
```
Following entries have been updated, because atomic compositions or bonding patterns were changed.
```
5Z8 8BA 9NG BP5 CLZ CV6 DG9 DLC ETA N8K O18 PFX Q75 Q78 QFW RHJ T0N X1J YOA
```
Note 8BA has wrong chemistry (both P-OP1 and P-OP2 were double bond) which was fixed manually.

There are some changes in following entries as well, but they couldn't be updated because of metals or borons.
```
1CL 39B FSO K3G OEX OEY PTT RAX RUX TPT
```

Needs testing before merging.

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
Did you report 8BA and others where there are chemistry changes to the PDB.
mtals will come soon. borons will have to wait.

**Comment by keitaroyam** [comment]
~Not yet, will do.~ done

Updated DG9-SER link
```
LINK: RES-NAME-1 DG9 ATOM-NAME-1 P2A RES-NAME-2 SER ATOM-NAME-2 OG DELETE ATOM O4 1
```

NOTE: T0N should be fixed; this acedrg seems to have a problem with atom name having two single quotations.

**Comment by keitaroyam** [comment]
T0N fixed (by a newer acedrg). still needs tests

**Comment by drlemmus** [comment]
T0N is only in one NMR model so I cannot test in pdb-redo.

**Comment by keitaroyam** [comment]
N8K is used in 6tg4 and 7pox. 6tg4 is good, but 7pox uses different atom names. I initially thought atom names have not been updated in 7pox, but they are also inconsistent with alt_atom_id (so updating in gemmi didn't help at all).

Similarly, X1J is inconsistent with both PDB entries (5sns and 5s65). Again alt_atom_id didn't help, which is (partly) incorrect.

**Comment by drlemmus** [comment]
I'll report those to the PDB annotators

**Comment by keitaroyam** [comment]
@drlemmus any update from the PDB?

**Comment by drlemmus** [comment]
Not yet, I'm afraid.

**Comment by keitaroyam** [comment]
7CQ in the CCD was fixed and that in our library was updated accordingly.

**Review by GaribMurshudov — APPROVED** [review]
It looks reasonable to me

**Comment by keitaroyam** [comment]
In the CCD, now `8NK BJ3 BQG HEK` are obsolete, and 6VO and X1J were updated. The X1J issue (inconsistent atom names in the pdb models) has been sorted.

**Comment by keitaroyam** [comment]
As discussed in #48, single-atom entries `ZCM RHF CF BS3 TA0 AM 4TI 0BE` have been added.

By the way, should we remove `RH RH3 BI TA BE` from the library? In the CCD, they don't exist, and `RHF BS3 TA0 0BE` exist instead.

**Comment by keitaroyam** [comment]
Redundant and CCD-nonexistent single atom entries `RH RH3 BI TA BE ER` have been removed

**Comment by GaribMurshudov** [comment]
Do we have replacements for these single atom monomers?

**Comment by keitaroyam** [comment]
Yes. They were Rh, Rh, Bi, Ta, Be, Er, respectively. Here is the summary of single-atom entries:

| Element | CCD | Monlib |
| ------- | --- | ------ |
| X | UNX |  |
| H |  |  H |
| D | D8U | D8U |
| He |  | HE |
| Li | LI | LI |
| Be | 0BE | 0BE |
| N |  | UNX |
| O | O | DUM O |
| F | F | F |
| Ne |  | NE |
| Na | NA | NA |
| Mg | MG | MG |
| Al | AL | AL |
| Si |  | SI |
| S |  | S |
| Cl | CL | CL |
| Ar | AR | AR |
| K | K | K |
| Ca | CA | CA |
| Sc |  | WSC |
| Ti | 4TI | 4TI |
| V | V | V |
| Cr | CR | CR |
| Mn | MN MN3 | MN MN3 |
| Fe | FE FE2 | FE FE2 |
| Co | 3CO CO | 3CO CO |
| Ni | 3NI NI | 3NI NI |
| Cu | CU CU1 CU3 | CU CU1 CU3 |
| Zn | ZN | ZN |
| Ga | GA | GA |
| Ge |  | GE |
| As | ARS | ARS |
| Se | SE | SE |
| Br | BR | BR |
| Kr | KR | KR |
| Rb | RB | RB |
| Sr | SR | SR |
| Y | Y1 YT3 | Y1 YT3 |
| Zr | ZR | ZR |
| Nb |  | NB |
| Mo | 4MO 6MO MO | 4MO 6MO MO |
| Ru | RU | RU |
| Rh | RH RH3 RHF | RHF |
| Pd | PD | PD |
| Ag | AG | AG |
| Cd | CD | CD |
| In | IN | IN |
| Sn |  | SN |
| Sb | SB | SB |
| Te | TE | TE |
| I | IOD | IOD |
| Xe | XE | XE |
| Cs | CS | CS |
| Ba | BA | BA |
| La | LA | LA |
| Ce | CE | CE |
| Pr | PR | PR |
| Nd | ND | ND |
| Pm |  | PM |
| Sm | SM | SM |
| Eu | EU EU3 | EU EU3 |
| Gd | GD GD3 | GD GD3 |
| Tb | TB | TB |
| Dy | DY | DY |
| Ho | HO HO3 | HO HO3 |
| Er | ER3 | ER3 |
| Tm |  | TM |
| Yb | YB YB2 | YB YB2 |
| Lu | LU | LU |
| Hf |  | HF |
| Ta | TA0 | TA0 |
| W | W | W |
| Re | RE | RE |
| Os | OS OS4 | OS OS4 |
| Ir | IR IR3 | IR IR3 |
| Pt | PT PT4 | PT PT4 |
| Au | AU AU3 | AU AU3 |
| Hg | HG | HG |
| Tl | TL | TL |
| Pb | PB | PB |
| Bi | BS3 | BS3 |
| Po |  | PO |
| At |  | AT |
| Rn |  | RN |
| Fr |  | FR |
| Ra |  | RA |
| Ac |  | AC |
| Th | TH | TH |
| U | U1 | U1 |
| Pu | 4PU | 4PU |
| Am | AM | AM |
| Cm | ZCM | ZCM |
| Cf | CF | CF |

**Pull request merged**
