### PR TITLE
add NSP/NSP1 energy types

### PR DESCRIPTION
**Pull request by keitaroyam**
Energy type NSP is used in 1299 monomers but has not been included in ener_lib.cif.

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
Have you added them to energy libraries?

**Comment by keitaroyam** [comment]
You can see them in "Files changed" tab - this is what you meant?

**Comment by keitaroyam** [comment]
I duplicated NS/NS1 as NSP/NSP1 in other places as well.

**Comment by keitaroyam** [comment]
@GaribMurshudov As it was asked, the number of affected PDB entries was 2463. The most popular monomer was SCN (and AZI).

**Comment by GaribMurshudov** [comment]
A lot.

It could affect only Hbonds I think

**Pull request merged**
