### PR TITLE
Update metal containing entries

### PR DESCRIPTION
**Pull request by keitaroyam**
Finally we will have reasonable restraints for metal containing entries. See the wiki article https://github.com/MonomerLibrary/monomers/wiki/Dealing-with-metals
Probably we will update all again before merging.

Should sort #23 and #36.

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
I thought #23 and #36 have been sorted out a long time ago. I can generate them again.

**Comment by keitaroyam** [comment]
I meant they should have been sorted in this branch. This needs to be confirmed.

**Comment by drlemmus** [comment]
There don't seem to be any angle restraint for the CL1 atom in 4IR which causes distortions in refinement (testcase 3pk2)

**Comment by drlemmus** [comment]
Regarding the point made in the wiki: leaving out "placeholder" atoms is risky for compounds where not always the same atoms leave. You could have a look at cisplatin for that as an example.

**Comment by GaribMurshudov** [comment]
We will need to explore alternative options.

**Comment by drlemmus** [comment]
So far the cases I looked at seem to be an improvement, sometimes very big. AG1 presents an interesting problem: if you look at PDB entry 2jld, you can see that the chirality of C6 is wrong, albeit consistent with the definition. In the associated paper you see that the main text has the chirality in the model, but the supplemental data about the synthesis has the inverted chirality. Changing the chirality to 'both' in the restraint file allows you to improve the model.

**Comment by GaribMurshudov** [comment]
@drlemmus I think one of the next steps should be validation of all pdb entries. Only after we have finished this stage: establish procedures and update dictionaries. We are close to that stage.
We will see interesting cases.

**Comment by keitaroyam** [comment]
Updated again. I think now this branch is ready for review. Please report any issues.
Note: for the actual refinement, restraints from metalCoord may be needed because metals may have different coordinations depending on the environment. See https://github.com/Lekaveh/MetalCoordAnalysis/blob/master/tutorial/tutorial.rst

**Review by GaribMurshudov — APPROVED** [review]
Hopefully these are good. At least they are better than current metal containing monomers

**Pull request merged**
