### PR TITLE
add peptide-DNA/RNA link

### PR DESCRIPTION
**Pull request by keitaroyam**
I created a link using Acedrg 256 with the following instruction
```
LINK: RES-NAME-1 ALA ATOM-NAME-1 C RES-NAME-2 A ATOM-NAME-2  O3' DELETE ATOM OXT 1
```
and replaced modifications with DEL-OXT and DEL_HO3p.

Some high resolution examples from PDB:
| PDB | resolution | source | atoms |
| -- | -- | -- | -- |
| 1vq8 | 2.2 A | X-ray | 4/PHE 77/C - 4/DA 76/O3' |
| 7o7y | 2.2 A | EM | BK/PHE 4399/C - AT/A 76/O3' |
| 7qi4 | 2.21 A | EM  | B/VAL 101/C - B/A 76/O3' |

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
I tried 1vq8. Gemmi gives these messages (there many of them):
Warning: Placing of hydrogen bonded to 0/U 12/O2' failed:
  Missing angle restraint HO2'-O2'-NA.

Warning: Placing of hydrogen bonded to 0/C 40/O2' failed:
  Missing angle restraint HO2'-O2'-NA.

**Comment by GaribMurshudov** [comment]
AA-RNA was recognised

**Comment by GaribMurshudov** [comment]
I have one worry about thi link. Bond length is 1.278. When I run acedrg agains using ALA and A as monomers this length become 1.334. The reason for such difference shuld be investigated. 
I used aceDRG version 256

**Comment by keitaroyam** [comment]
There was a problem in acedrg 256 installation. I updated bond/angle values using acedrg 259.

**Comment by keitaroyam** [comment]
Refinement tested using 1vq8 with Refmac5.8.0386_rev446. It looks good.

**Pull request merged**
