### PR TITLE
Renaming atoms as per the remediation of atom names in peptide backbones

### PR DESCRIPTION
**Pull request by keitaroyam**
Last month, atom names of several peptide(-like) monomers were updated https://www.wwpdb.org/news/news?year=2023#654a801dd78e004e766a96bd #39 #37.

Here 828 entries have been updated, and 202 entries no longer need aliases. Links and modifications have also been updated.

This was done using a custom made script in https://github.com/MonomerLibrary/Ligand-Tools/tree/main/fix-groups, without using AceDRG.
```sh
python rename_atoms.py ~/prog/monomers components.cif.gz  < monomer_list.txt 
python post_acedrg.py ~/prog/monomers/?/
python fix_monlib_list.py --monlib ~/prog/monomers
```
with [monomer_list.txt](https://github.com/MonomerLibrary/monomers/files/13764152/monomer_list.txt) prepared by @wojdyr, and components.cif.gz as of Dec 23, 2023.

Now these entries have `_chem_comp_atom.alt_atom_id` which store the old atom names. Refmacat and Servalcat can handle model files with the old names, thanks to gemmi (from 0.6.4).

Also, an unnecessary file (a/libcheck.lib) and unnecessary blocks (global_ and data_) in some files have been removed.

### CODE REVIEW

**Comment by keitaroyam** [comment]
@drlemmus Could you run any tests using this branch?

**Comment by keitaroyam** [comment]
A bug in the script was fixed; actually 290 entries (instead of 202) no longer need aliases.

**Comment by drlemmus** [comment]
Tested and no errors found so far.

**Comment by keitaroyam** [comment]
Thank you Robbie. It seems good to me as well (just tested topology creation using gemmi, with affected pdb entries).

**Review by GaribMurshudov — APPROVED** [review]
I approve this. however, we will need further tests. I think within ccp4 these tests will be done.

**Pull request merged**
