### PR TITLE
fix PJE-CYS and CYS-HEMB

### PR DESCRIPTION
**Pull request by keitaroyam**
Original title: missing new_atom_id.

They are needed for gemmi, while Refmac seems to already take care of this kind of error. Anyway that was an error of the dictionary. Will need to test.

### CODE REVIEW

**Comment by keitaroyam** [comment]
Testing it, I found several problems with these links and fixed them.

PJE-CYS: PJEmod2 was insufficient and caused a "Unhandled topology of 2 hydrogens bonded to C21" problem in gemmi. So I updated this link using Acedrg 269:
```
LINK: RES-NAME-1 PJE ATOM-NAME-1 C20 RES-NAME-2 CYS ATOM-NAME-2 SG CHANGE BOND C20 C21 SINGLE 1
```

HEMmod2: it was deleting wrong plane (plan-10), which was now corrected to plan-8.

CYS-HEMC: added for completeness (CAC side version of CYS-HEMB). Created by replacing atoms
```sh
sed -e "s/CAB/CAC/; s/HAB/HAC/; s/CBB/CBC/; s/HBBA/HBCA/; s/HBB/HBC/; s/C3B/C3C/; s/C2B/C2C/; s/H33/H34/; s/plan-8/plan-10/; s/HEMmod2/HEMmod3/; s/CYS-HEMB/CYS-HEMC/" CYS-HEMB.cif
```

I used PDB 2amq and 2e84 for the test.

**Comment by keitaroyam** [comment]
HEMmod2 and HEMmod3 had unupdated angle restraints, as pointed out by Garib. Fixed.

**Comment by GaribMurshudov** [comment]
I think for PJEmod2 the following modifications (related to H4 of PJE) should be added. they were missing in my copy (I may have mixed up things again):

**PJEmod2 change C22 C21 H4  108.416 1.50
PJEmod2 change C20 C21 H4 108.757 1.50**

I have added in my local branch. I am worried that I may mix things up if i commit this.

**Comment by keitaroyam** [comment]
You can check changes in the "Files changed" tab above. There is
```
PJEmod2 change C20 C21 H4 108.891 1.50
```
but that for C22-C21-H4 is missing.

**Comment by GaribMurshudov** [comment]
This should be fixed by acedrg. Let us discuss this today. If we are to use acedrg for link generation it should do things properly.

**Comment by keitaroyam** [comment]
PJE-CYS has been updated using Acedrg 271, and PJEmod2 has changed. Also manually updated _chem_mod_tor of HEMmod2 and HEMmod3, where id and new_period were missing.

Note that gemmi has ignored _chem_mod_tor having no id or new_period. Now it's also fixed https://github.com/project-gemmi/gemmi/commit/ed72fc2d7597748b712995f1ccf883179dc97a92

**Comment by GaribMurshudov** [comment]
Good. You could merge them.

**Pull request merged**
