### PR TITLE
Added missing compounds. Note P3C is made with libcheck

### PR DESCRIPTION
**Pull request by drlemmus**
Added a few missing compounds that were new in the PDB. Could you merge these into the release?

### CODE REVIEW

**Comment by keitaroyam** [comment]
I can only see mon_lib_list. You didn't add files?

**Comment by GaribMurshudov** [comment]
All added monomers should be tested by two users. It will make sure that errors will notbe accumulated. 
If P3C was generated by libcheck I need to check it a bit more carefully.

**Comment by GaribMurshudov** [comment]
Is P3C really different? or is it PC4 with on CL replaced by something else? Density I looked at did was not convincing. However, you are right. If it is in CCD then we could add it (after checking carefully) into our monomer library.

There is a general questions: Should we keep increasing the monomer library or should I have another list for additional monomers?

**Comment by drlemmus** [comment]
I think the CCP4ML should reflect the CCD as much as possible so that we can read any PDB entry and do something with it. If there are nonsense entries in the CCD we should try to have them changed. I'm happy to go after that as I have been doing that a lot anyway.
I'd rather not go back to having a set of compounds with 'minimal description'. That is so 2006.

**Pull request closed without merging**
