### PR TITLE
Fix hydrides

### PR DESCRIPTION
**Pull request by keitaroyam**
XH<sub>n</sub> entries have not been updated (although some of them were wrong), since Acedrg could not handle them. Now it's possible, and they were regenerated using Acedrg 285. Some angles may need further corrections. Links should be updated also.

for the pep-NH2 link:
```
LINK: RES-NAME-1 ALA ATOM-NAME-1 C RES-NAME-2 NH2 ATOM-NAME-2 N DELETE ATOM OXT 1 DELETE ATOM H 2
```

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
Should I approve it after we have done proper analysis for HOH? Why I am on it it would be good to have a list of such molecules so that I can try to do analysis using COD.

**Comment by keitaroyam** [comment]
I would like to wait for the proper analysis.

**Comment by GaribMurshudov** [comment]
Ok.

**Comment by keitaroyam** [comment]
Now the pep-NH2 link was updated and this PR is ready for review.
Although water's angle (107.4) is a bit different from the famous value (104.5), it follows the acedrg procedure and may be acceptable?

**Comment by keitaroyam** [comment]
Note that this PR also fixes the energy type of N of NH4. That was NT (hydrogen bond incapable) and lead to a wrong critical distance.

**Review by wojdyr — APPROVED** [review]
Looks good.

**Pull request merged**
