### PR TITLE
remove redundant files

### PR DESCRIPTION
**Pull request by keitaroyam**
removing
* dnarna_basepairs.txt
* dnarna_basepairs_2.txt
* list/dnarna_basepairs.txt
* list/dnarna_basepairs_2.txt

Only dnarna_params.txt is needed. Refmac needs to be fixed just in case.

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
Should we also remove G:U and add three seperate G:U parameter files or make another set of unusual parameter files?

**Comment by keitaroyam** [comment]
Let us discuss it elsewhere. Here is just to remove redundant files (any other files may be deleted?)

**Review by GaribMurshudov — APPROVED** [review]

**Comment by GaribMurshudov** [comment]
Ok

**Comment by keitaroyam** [comment]
Perhaps this should be merged after Refmac is fixed?

**Comment by GaribMurshudov** [comment]
It will not have affect on refmac. This file is read only if particular keyword is given, nobody is aware of this option.
In any case I will commit a version of refmac today.

**Comment by keitaroyam** [comment]
I see in Refmac5.8.0421_rev484 dnarna_basepairs.txt was changed to dnarna_params.txt. Thanks.

**Pull request merged**
