### PR TITLE
ener_lib: fix N types

### PR DESCRIPTION
**Pull request by keitaroyam**
Created on behalf of @GaribMurshudov 
> I added N30, N31, N32, N33 as atom types for N with three bonds. No H, with 1,2 and 3 hydorgen atoms. 3 H atoms can only be for NH3. I also added NT4.

### CODE REVIEW

**Comment by GaribMurshudov** [comment]
At the moment I have not changed any monomer entry. If we think that these additions are good then we can start changing the monomer library. Please check and give some feedback.

**Comment by GaribMurshudov** [comment]
We need to work on this a bit more. 
We need to add hybridisation state of atom types for easy access to atom types. 
We also need to test atom types on monomers generated by acedrg.

**Comment by GaribMurshudov** [comment]
Ok. Now we need to deal witht this problem and links. For links we will need a seperate branch.
Here, we would like to expand and correct energy types. There are several things we will need to consider:
1) three types of N: sp2, sp3 with three bonds and 2p3 with four bonds (with N+1). Do we need to consider sp2 with N+1? E.g NH1 or NH2 of Arg. I do not think we need to do anything special at the moment for this case
2) how to deal with protonations. Examples are ND1 and NE2 of His. One, both or none of them may have H atom attached. Do we need to have different atom types? These cases may only be dealt with during refinement and model building
3) Similar situation is with carboxyl groups
4) Do we need special atom types on S and P when oxygens are involved in metal bond or one of them can be protonated. Do we need to deal with them? Do we have use cases for them?

**Review by GaribMurshudov — APPROVED** [review]

**Comment by keitaroyam** [comment]
Why was NSP deleted? It seems 1441 monomers were affected (see the CI log).

**Comment by GaribMurshudov** [comment]
Did I delete NSP? Although, most of NSP?
I restored them. I made NSP as an acceptor, NSP1 as donor. 
NSP1 would be something like:    triple bond N(+1) - H, NSP would be something like: triple bond N
there is a question of how to deal with N=N=N  (with chargesmoving around). What should be atom type for the middle N

**Comment by keitaroyam** [comment]
Thanks. It seems to have been deleted in the first commit. I think it's better to include updated monomers using new energy types.

**Comment by GaribMurshudov** [comment]
But it will take time. If we update all monomers again (which we should) then we need to do extensive tests. 
I think it can be done after May.

**Review by GaribMurshudov — COMMENTED** [review]
These changes look good for me

**Comment by keitaroyam** [comment]
Examples from Garib:

Ligand      Atom    Atom type
KEN           NE1         N30
DMN         N1           N31
NEH          N             N32
TMA    N1     NT (NT0 or NT or N)
TEA     N        NT1
GPJ     N1     NT2
LYS      NZ     NT3

added updated KEN/DMN/NEH files as examples

**Comment by keitaroyam** [comment]
Note that we needed to merge this, because a new acedrg v273 that may assign these new energy types will be released in the next CCP4 update

**Pull request merged**
